#!/usr/bin/env bash
#
# One-command deployment for Lumina LMS on a fresh on-prem VM.
#
#   ./deploy.sh
#
# That is the whole interface for the common case. It is idempotent: running it
# again rebuilds and restarts the existing stack rather than duplicating anything,
# and it never regenerates a secret that already exists, since that would silently
# invalidate every signed-in session.
#
# What it does, in order:
#   1. Checks Docker and Docker Compose are present.
#   2. Generates .env.docker with a random AUTH_SECRET on first run only.
#   3. Builds the image and starts the stack.
#   4. Polls /api/health until the app answers, or fails loudly with the logs.
#
# Flags:
#   --seed                Load the demo dataset (courses, sample people) instead
#                          of starting empty. Without it, the first account
#                          anyone registers becomes the administrator.
#   --port PORT            Host port to publish on. Default 4400.
#   --org-name "Name"      Sets NEXT_PUBLIC_ORG_NAME shown in the UI.
#   --domain DOMAIN         Enables the optional Caddy reverse proxy and
#                          requests a Lets Encrypt certificate for DOMAIN.
#                          Requires ports 80 and 443 reachable from the
#                          internet and DNS already pointed at this host,
#                          since Lets Encrypt validates both before issuing.
#   --postgres              Also starts a PostgreSQL container and points the
#                          app at it instead of SQLite. Requires
#                          prisma/schema.prisma's datasource provider to
#                          already be set to "postgresql" (see README) --
#                          this flag does not edit the schema for you.
#
# Re-running with different flags updates .env.docker and restarts the stack
# with the new values; it does not touch data in the named volumes.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE=".env.docker"
PORT=""
ORG_NAME=""
DOMAIN=""
SEED="false"
USE_POSTGRES="false"

c_reset=$'\033[0m'; c_bold=$'\033[1m'; c_dim=$'\033[2m'
c_green=$'\033[32m'; c_red=$'\033[31m'; c_yellow=$'\033[33m'; c_cyan=$'\033[36m'
# Disable colour when not attached to a terminal (e.g. piped into a log file).
if [ ! -t 1 ]; then c_reset=""; c_bold=""; c_dim=""; c_green=""; c_red=""; c_yellow=""; c_cyan=""; fi

log()  { echo "${c_cyan}->${c_reset} $*"; }
ok()   { echo "${c_green}OK${c_reset} $*"; }
warn() { echo "${c_yellow}!${c_reset} $*"; }
die()  { echo "${c_red}${c_bold}FAILED: $*${c_reset}" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --seed) SEED="true"; shift ;;
    --port) PORT="${2:?--port needs a value}"; shift 2 ;;
    --org-name) ORG_NAME="${2:?--org-name needs a value}"; shift 2 ;;
    --domain) DOMAIN="${2:?--domain needs a value}"; shift 2 ;;
    --postgres) USE_POSTGRES="true"; shift ;;
    -h|--help)
      sed -n '2,36p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) die "Unknown flag: $1 (see --help)" ;;
  esac
done

echo ""
echo "${c_bold}Lumina LMS -- deploy${c_reset}"
echo ""

# --- 1. Docker present? -----------------------------------------------------

if ! command -v docker >/dev/null 2>&1; then
  die "Docker is not installed. See README.md for install commands per OS."
fi

if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  die "Docker is installed but Compose is not. Install the compose plugin (apt or dnf install docker-compose-plugin)."
fi
ok "Docker and Compose found ($DC)"

if ! docker info >/dev/null 2>&1; then
  die "Docker is installed but not usable by this user. Run with sudo, or add yourself to the docker group and re-login: sudo usermod -aG docker \"\$USER\""
fi

# --- 2. Environment file -----------------------------------------------------
#
# A dedicated .env.docker rather than the repos dev .env: the two need different
# shapes for the same key. Local development sets DATABASE_URL to a path relative
# to the project (file:./dev.db); the container needs an absolute path inside its
# own filesystem (file:/app/data/lumina.db). Sharing one file would mean whichever
# workflow ran npm run setup last silently breaks the other -- the entrypoint
# guard added for exactly this class of mistake would refuse to start the
# container with devs relative path. Separate files, no collision.

if [ -f "$ENV_FILE" ]; then
  ok "$ENV_FILE already exists -- keeping its AUTH_SECRET"
  set -a; source "$ENV_FILE"; set +a
else
  log "Generating $ENV_FILE..."

  if command -v openssl >/dev/null 2>&1; then
    SECRET="$(openssl rand -base64 32)"
  else
    SECRET="$(head -c 32 /dev/urandom | base64 | tr -d '\n')"
  fi

  {
    echo "# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit this file --"
    echo "# it holds the key every session is signed with. Delete it to force a fresh"
    echo "# secret (this signs every existing session out), or edit values below and"
    echo "# re-run ./deploy.sh to apply them."
    echo ""
    echo "AUTH_SECRET=\"${SECRET}\""
    echo "DATABASE_URL=\"file:/app/data/lumina.db\""
    echo "HOST_PORT=\"${PORT:-4400}\""
    echo ""
    echo "AUTH_ALLOW_SELF_REGISTRATION=\"true\""
    echo "AUTH_ALLOWED_EMAIL_DOMAINS=\"\""
    echo ""
    echo "NEXT_PUBLIC_APP_NAME=\"Lumina\""
    echo "NEXT_PUBLIC_APP_TAGLINE=\"Learning, elevated.\""
    echo "NEXT_PUBLIC_ORG_NAME=\"${ORG_NAME:-Your Organization}\""
    echo ""
    echo "SEED_ON_START=\"${SEED}\""
  } > "$ENV_FILE"

  ok "Wrote $ENV_FILE with a fresh AUTH_SECRET"
fi

# Flags always win on a re-run, even over a previously generated file.
#
# set_env_var replaces an existing KEY="..." line in place, or appends one if the
# key is not there yet. Using it everywhere (rather than an unconditional `>>` for
# keys we happen to know are "new") matters concretely for DATABASE_URL below: the
# generator above always writes a SQLite DATABASE_URL, so a plain append under
# --postgres would leave two DATABASE_URL lines in the file. Both bash `source`
# and Compose's --env-file parsing happen to let the later line win, so it would
# still *work*, but a file that silently depends on line order to be correct is
# exactly the kind of thing that stops working the next time someone hand-edits
# it. One key, one line, always.
set_env_var() {
  local key="$1" value="$2"
  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    sed -i.bak "s#^${key}=.*#${key}=\"${value}\"#" "$ENV_FILE" && rm -f "${ENV_FILE}.bak"
  else
    echo "${key}=\"${value}\"" >> "$ENV_FILE"
  fi
}

[ -n "$PORT" ] && set_env_var HOST_PORT "$PORT"
[ -n "$ORG_NAME" ] && set_env_var NEXT_PUBLIC_ORG_NAME "$ORG_NAME"
[ "$SEED" = "true" ] && set_env_var SEED_ON_START "true"
[ -n "$DOMAIN" ] && set_env_var DOMAIN "$DOMAIN"

set -a; source "$ENV_FILE"; set +a
PUBLISHED_PORT="${HOST_PORT:-4400}"

# --- 3. Build and start -------------------------------------------------------

PROFILES=()
if [ "$USE_POSTGRES" = "true" ]; then
  PROFILES+=(--profile postgres)
  if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    if command -v openssl >/dev/null 2>&1; then
      PG_PASS="$(openssl rand -base64 24)"
    else
      PG_PASS="$(head -c 24 /dev/urandom | base64 | tr -d '\n')"
    fi
    set_env_var POSTGRES_PASSWORD "$PG_PASS"
    set_env_var DATABASE_URL "postgresql://lumina:${PG_PASS}@postgres:5432/lumina?schema=public"
    warn "Generated a PostgreSQL password in $ENV_FILE. Set the schemas datasource"
    warn "provider to postgresql in prisma/schema.prisma before this will connect --"
    warn "see README.md, section With PostgreSQL."
    set -a; source "$ENV_FILE"; set +a
  fi
fi
if [ -n "$DOMAIN" ]; then
  PROFILES+=(--profile proxy)
fi

log "Building the image (first run takes a few minutes)..."
$DC --env-file "$ENV_FILE" "${PROFILES[@]}" build

log "Starting the stack..."
$DC --env-file "$ENV_FILE" "${PROFILES[@]}" up -d

# --- 4. Wait for health --------------------------------------------------------

log "Waiting for the app to become healthy..."
ATTEMPTS=0
MAX_ATTEMPTS=40
until curl -fsS "http://127.0.0.1:${PUBLISHED_PORT}/api/health" >/dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
    echo ""
    echo "${c_red}${c_bold}The app did not become healthy in time.${c_reset}" >&2
    echo "Recent logs:" >&2
    $DC --env-file "$ENV_FILE" logs --tail=80 app >&2 || true
    echo "" >&2
    echo "Common causes: the image is still finishing its first build (retry this script)," >&2
    echo "or DATABASE_URL/AUTH_SECRET in $ENV_FILE do not match what the container expects." >&2
    exit 1
  fi
  printf "."
  sleep 3
done
echo ""
ok "Healthy"

# --- Done ----------------------------------------------------------------------

# `|| true` on each line matters under `set -euo pipefail`: without it, a
# non-zero exit from `hostname -I` on a system where it is unsupported (not all
# hostname implementations have -I, and pipefail propagates that through the
# pipe to awk) would kill the script via errexit right here -- after the app is
# already up and healthy, but before this banner, the only place the URL is
# printed, ever runs. Confirmed this by hitting it directly in a shell that
# lacks GNU hostname's -I.
HOST_ADDR="$(hostname -I 2>/dev/null | awk '{print $1}')" || true
[ -z "$HOST_ADDR" ] && { HOST_ADDR="$(hostname)" || true; }

echo ""
echo "${c_bold}${c_green}Lumina LMS is running.${c_reset}"
echo ""
if [ -n "$DOMAIN" ]; then
  echo "  ${c_cyan}https://${DOMAIN}${c_reset}  ${c_dim}(certificate issued automatically on first request)${c_reset}"
else
  echo "  ${c_cyan}http://${HOST_ADDR}:${PUBLISHED_PORT}${c_reset}  ${c_dim}(also http://localhost:${PUBLISHED_PORT} on this machine)${c_reset}"
fi
echo ""
if [ "$SEED" = "true" ]; then
  echo "  Demo accounts (password ${c_bold}Password123!${c_reset} for all):"
  echo "    admin@example.com       (Admin)"
  echo "    instructor@example.com  (Instructor)"
  echo "    learner@example.com     (Learner)"
else
  echo "  No demo data was loaded. ${c_bold}Register the first account${c_reset} -- it becomes"
  echo "  the administrator automatically."
fi
echo ""
if [ -z "$DOMAIN" ]; then
  echo "  ${c_yellow}This is serving plain HTTP.${c_reset} Fine on a trusted internal network for a"
  echo "  quick look; put TLS in front before anyone else relies on it -- session"
  echo "  cookies travel in clear text otherwise. Two options:"
  echo "    - Point a domain at this host and re-run: ./deploy.sh --domain lms.example.com"
  echo "    - Or terminate TLS with your own nginx, Caddy, or load balancer in front."
  echo ""
fi
echo "  ${c_dim}Useful commands:${c_reset}"
echo "    $DC --env-file $ENV_FILE logs -f app     # tail logs"
echo "    $DC --env-file $ENV_FILE down             # stop"
echo "    ./deploy.sh                                 # rebuild and restart after a git pull"
echo ""
