/**
 * Single source of truth for the film.
 *
 * `osd` is the headline burned into the frame and `sub` the line under it.
 * In a silent cut those two carry everything the narration would have, so `sub`
 * is the narration compressed to one readable line rather than a caption of it.
 * `vo` is kept for the voiced version and for the script.
 */
export const ACTS = { Build: "I", Administer: "II", Learn: "III", Complete: "IV", Prove: "V" };

export const SCENES = [
  { act: "Build", d: 5, card: "Lumina", sub: "Learning, elevated.",
    vo: "This is Lumina." },

  { act: "Build", d: 9, img: "12-instructor",
    osd: "It starts with an expert",
    sub: "Courses are built in-house. No vendor, no content licence.",
    vo: "Every course in Lumina starts with someone inside your organisation who already knows the subject. No vendor. No content licence." },
  { act: "Build", d: 10, img: "12b-course-builder",
    osd: "Sections, lessons, quizzes",
    sub: "Video, articles, resources — and quizzes that explain the wrong answers.",
    vo: "They build it here. Sections, video lessons, articles, downloadable resources. And quizzes, with explanations written for the people who get it wrong." },
  { act: "Build", d: 7, img: "15b-admin-courses",
    osd: "Published when it's ready",
    sub: "A course stays a draft until somebody decides it is finished.",
    vo: "Nothing goes live by accident. A course stays a draft until somebody decides it is finished." },

  { act: "Administer", d: 9, img: "13b-admin-people",
    osd: "People, roles, departments",
    sub: "Priya sets up who is who, and what each person can reach.",
    vo: "Meanwhile Priya, who runs learning and development, sets up the people. Name, department, and the role that decides what they can reach." },
  { act: "Administer", d: 8, img: "13c-admin-roles",
    osd: "Three roles, clear edges",
    sub: "Learner, instructor, administrator — with guards on the dangerous edits.",
    vo: "Learner, instructor, administrator. Guards stop her removing her own access, or deactivating the last administrator standing." },
  { act: "Administer", d: 10, img: "A1-assign-filled",
    osd: "A due date that means something",
    sub: "Compliance training assigned with a real deadline, and a reason.",
    vo: "Then she assigns the compliance course. A real due date, and a note explaining why it has landed in somebody's week." },
  { act: "Administer", d: 8, img: "A2-assign-by-department",
    osd: "Assigning also enrols",
    sub: "Sent to a whole department at once. Nobody has to go looking for it.",
    vo: "She filters by department and sends it to all of Engineering at once. Assigning also enrols them, so nobody has to go looking for it." },

  { act: "Learn", d: 7, img: "03-signin-light",
    osd: "Meet Daniel",
    sub: "An engineer who has just been given something to do.",
    vo: "Which brings us to Daniel, an engineer who has just been given something to do." },
  { act: "Learn", d: 9, img: "04-dashboard",
    osd: "It's already waiting",
    sub: "In progress, due, and overdue — the moment he signs in.",
    vo: "It is waiting when he signs in. What is in progress, what is due, and the compliance course flagged with the days remaining." },
  { act: "Learn", d: 8, img: "05-catalog",
    osd: "Every view is a link",
    sub: "Search and filters live in the address bar, so any view is shareable.",
    vo: "He can also go looking. Search across titles, topics and instructors. Every filter lives in the address bar, so any view is a link he can send a colleague." },
  { act: "Learn", d: 8, img: "06-course-page",
    osd: "Know before you commit",
    sub: "Objectives, requirements, and what everyone else made of it.",
    vo: "Course pages tell him what he will learn before he commits. Objectives, requirements, who it is for, and what everyone else made of it." },
  { act: "Learn", d: 11, img: "07-player",
    osd: "Picks up where he left off",
    sub: "Speed control, keyboard shortcuts, and a position that is remembered.",
    vo: "Then he learns. Speed control, keyboard shortcuts, and a remembered position, so finishing it on a phone at seven in the morning simply works." },
  { act: "Learn", d: 7, img: "L1-notes",
    osd: "Notes stay private",
    sub: "His notes. No instructor or administrator can read them.",
    vo: "He keeps notes against the lesson. They are his. No instructor, no administrator, nobody else can read them." },
  { act: "Learn", d: 8, img: "L2-qa",
    osd: "Questions reach the author",
    sub: "And the answer stays with the lesson for whoever comes next.",
    vo: "When something does not land, he asks. The question goes to the person who wrote the course, and the answer stays with the lesson for whoever comes next." },
  { act: "Learn", d: 8, img: "L3-quiz-answering",
    osd: "Graded on the server",
    sub: "The answer key never reaches the browser.",
    vo: "Then the knowledge check. Single choice, multi-select, true or false. Graded on the server, so the answer key never reaches the browser." },
  { act: "Learn", d: 9, img: "L4-quiz-graded",
    osd: "Wrong answers explain themselves",
    sub: "Which is the part that turns a test into teaching.",
    vo: "And when he gets one wrong, it tells him why. That is the part that turns a test into teaching." },

  { act: "Complete", d: 7, img: "08b-my-learning",
    osd: "In progress, and finished",
    sub: "Progress grouped so he always knows what is left.",
    vo: "His progress follows him. In progress, not started, completed, grouped so he always knows what is left." },
  { act: "Complete", d: 8, img: "09b-path-detail",
    osd: "Onboarding, sequenced",
    sub: "Paths chain courses together, one step leading into the next.",
    vo: "Individual courses become paths. Onboarding sequenced properly, one step leading into the next, enrolling him in every course it contains." },
  { act: "Complete", d: 9, img: "10b-certificate",
    osd: "Issued the moment he finishes",
    sub: "Verification serial, printable, and nobody chasing anybody for proof.",
    vo: "He finishes, and the certificate issues itself. A verification serial, printable, and nobody chasing anybody for proof it happened." },
  { act: "Complete", d: 7, img: "11-leaderboard",
    osd: "Top ten only",
    sub: "Where he stands is his to see, and nobody else's.",
    vo: "There is a leaderboard, and it only ever shows the top of it. Where Daniel stands is his to see, and nobody else's." },

  { act: "Prove", d: 10, img: "13-admin-overview",
    osd: "The whole organisation, at a glance",
    sub: "Completion by department, and what is quietly stalling.",
    vo: "Back with Priya, it has all added up. Completion by department, what is being taken, and what is quietly stalling." },
  { act: "Prove", d: 9, img: "14-required-training",
    osd: "Who has finished, who hasn't",
    sub: "Filtered to whichever answer she needs today.",
    vo: "The register tells her exactly who has finished and who has not, filtered to whichever answer she needs today." },
  { act: "Prove", d: 10, img: "14b-required-overdue",
    osd: "Reminders on a schedule",
    sub: "In the app and by email — and the whole picture exports in one click.",
    vo: "Reminders go out on a schedule rather than when somebody remembers. In the app and by email, without nagging. And the whole compliance picture exports to a spreadsheet in one click." },
  { act: "Prove", d: 11, img: "25-sso-signin",
    osd: "One app. One database.",
    sub: "Single sign-on through your directory. On your servers, if that is the policy.",
    vo: "All of it runs as one application and one database. Single sign-on through the directory you already have. On your own servers, if that is what your policy says. No broker, no cluster, no per-seat surprise." },
  { act: "Prove", d: 6, card: "Learning, elevated.", sub: "lumina.example.com",
    vo: "Lumina. Learning, elevated." }
];
